# permissions for end users to view deploymentversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentversion-viewer-role
rules:
- apiGroups:
  - kyaninus.codepraxis.com
  resources:
  - deploymentversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kyaninus.codepraxis.com
  resources:
  - deploymentversions/status
  verbs:
  - get
